### PR TITLE
Major Update

### PR DESCRIPTION
**Pull request by tobiabocchi**
I have reformatted the code and modified part of the logic, following the communication protocol as defined [here](https://phreakerclub.com/447). The brute force should terminate much faster but I do not have a gate to test it with right now, if it does the `repetition` parameter could be lowered even further. Now It should also be easier to adapt it to generate files for other fixed code protocols.

### CODE REVIEW

**Comment by BitcoinRaven** [comment]
Unfortunately skipping the "pause period" between each keys will not work, I'm not sure if its flipper hardware limitation or what, but what will happen that the flipper drops around 10-15% of the keys sent, so this is essential for the code, this is the lowest time that I found that can be safely used without the keys dropped.

Any repetition less than 4 also will not work as well, regardless I will try the files to double check again. 

Thanks

**Comment by BitcoinRaven** [comment]
well after some testing the pause period is not needed, what I found it was a limitation in my receiver hardware that I used to test for the sent signals, I need to test the new script on the gate first to check for the required repetition number

**Comment by tobiabocchi** [comment]
Did you test my files on the gate? From experience, I can say that in my case it worked with a repetition of 3 using arduino and a generic 433MHz transmitter module

**Comment by BitcoinRaven** [comment]
Not yet, I will do that later today, Arduino sketches recognize the code, but I need to test it on the actual gate, as far as I remember I tried to reduce the repetition before and it didn't work, I will get back to you really soon with the results

**Comment by tobiabocchi** [comment]
I was able to test my .sub file, it works!

**Comment by BitcoinRaven** [comment]
Thats perfect, I will test it later today as well, thanks

**Pull request merged**
